### ISSUE TITLE
实际运行时报三个错

### ISSUE THREAD

**Issue by tiller2008** [monkeyk/MyOIDC#2]
1. client报Exception processing template "index": Error resolving template "index"
server报数据库嵌入失败
解决：经过排查发现，application.properties被编译在war包之外所致，注释掉client和server中pom.xml中的
```
<warSourceExcludes>*/classes/application.properties</warSourceExcludes>
<packagingExcludes>*/classes/application.properties</packagingExcludes>
```

2. Could not resolve placeholder 'application.host' in value "${application.host}"
解决（临时）：将application.host从application.properties的值，直接替换到MyOIDCConfiguration中去

3. mysql驱动报红
解决：将pom内的mysql相关的runtime在IDEA内修改为compile

本来想提交pull request，但是又担心自己水平有限，让人贻笑大方，so提交issue望大牛给予点评。
我还是个菜鸟，正在找认证方面的资料，看到大牛的java源码实现，很受启发，待大牛可以多多共享，O(∩_∩)O谢谢！

**Comment by monkeyk** [comment]
收到，
提到项目的 ISSUE中吧。会跟进



monkeyk@shengzhaoli.com
 
发件人： tiller2008
发送时间： 2019-02-01 16:50
收件人： monkeyk/MyOIDC
抄送： Subscribed
主题： [monkeyk/MyOIDC] 实际运行时报三个错 (#2)
client报Exception processing template "index": Error resolving template "index"
server报数据库嵌入失败
解决：经过排查发现，application.properties被编译在war包之外所致，注释掉client和server中pom.xml中的
<warSourceExcludes>*/classes/application.properties</warSourceExcludes>
<packagingExcludes>*/classes/application.properties</packagingExcludes>

Could not resolve placeholder 'application.host' in value "${application.host}"
解决（临时）：将application.host从application.properties的值，直接替换到MyOIDCConfiguration中去
我还是个菜鸟，正在找认证方面的资料，看到大牛的java源码实现，很受启发，待大牛可以多多共享，O(∩_∩)O谢谢！

**Comment by monkeyk** [comment]
更新最新
